name: Build with Localstack and Nix

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.*'
      - '**/*.md'
      - '**/*.org'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run `nix flake check`
      - run: nix flake check
      - name: Test deploy infrastructure
      - run: |
          docker pull localstack/localstack
          nix develop -c ./infra/deploy
