name: Build with Localstack and Nix

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.*'
      - '**/*.md'
      - '**/*.org'
  workflow_dispatch:

jobs:
  Build:
    runs-on: builder
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Test deploy infrastructure
        run: nix develop -c ./infra/deploy-tf.sh --verbose
