name: Build with Localstack and Nix

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.*'
      - '**/*.md'
      - '**/*.org'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      # - name: Run `nix flake check # run locally instead`
      #   run: nix flake check
      # - name: Build Localstack docker image
      #   run: nix build -L .#localstackpro-image
      # - name: Build Nardo docker image
      #   run: nix run .#nardo-image
      - name: Test deploy infrastructure
        run: nix develop -c ./infra/deploy
